-- A new stream will be created for the output of this pipeline.
-- The stream name will match the name used in the 'insert' statement.
insert into cleansed_processes
select 
        `name` as osquery_name,
        hostIdentifier,
        calendarTime,
        cast(unixTime as bigint) as unixTime,
        cast(epoch as bigint) as epoch,
        cast(counter as int) as counter,
        cast(numerics as boolean) as numerics,
        columns['cmdline'] as cmdline,
        columns['cwd'] as cwd,
        cast(columns['disk_bytes_read'] as bigint) as disk_bytes_read,
        cast(columns['disk_bytes_written'] as bigint) as disk_bytes_written,
        cast(columns['egid'] as int) as egid,
        cast(columns['euid'] as int) as euid,
        cast(columns['gid'] as int) as gid,
        columns['name'] as process_name,
        cast(columns['nice'] as int) as nice,
        cast(columns['on_disk'] as int) as on_disk,
        cast(columns['parent'] as bigint) as parent,
        columns['path'] as path,
        cast(columns['pgroup'] as bigint) as pgroup,
        cast(columns['pid'] as bigint) as pid,
        cast(columns['resident_size'] as bigint) as resident_size,
        columns['root'] as root,
        cast(columns['sgid'] as int) as sgid,
        cast(columns['start_time'] as bigint) as start_time,
        cast(columns['state'] as int) as state,
        cast(columns['suid'] as int) as suid,
        cast(columns['system_time'] as bigint) as `system_time`,
        cast(columns['threads'] as int) as threads,
        cast(columns['total_size'] as bigint) as total_size,
        cast(columns['uid'] as int) as uid,
        cast(columns['user_time'] as bigint) as user_time,
        cast(columns['wired_size'] as int) as wired_size,
        action
from filtered_processes
