version: "3.8"

services:
  jobmanager:
    build: 
      context: flink
      #dockerfile: Dockerfile.hive239
      #dockerfile: Dockerfile.no-hive
      dockerfile: Dockerfile.hive313
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
    - AWS_ACCESS_KEY_ID=admin
    - AWS_SECRET_ACCESS_KEY=password
    - AWS_REGION=us-east-1
    - AWS_DEFAULT_REGION=us-east-1
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager
      rest.flamegraph.enabled: true
  taskmanager:
    build: 
      context: flink
      #dockerfile: Dockerfile.hive239
      #dockerfile: Dockerfile.no-hive
      dockerfile: Dockerfile.hive313
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 2
    environment:
    - AWS_ACCESS_KEY_ID=admin
    - AWS_SECRET_ACCESS_KEY=password
    - AWS_REGION=us-east-1
    - AWS_DEFAULT_REGION=us-east-1
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager
      taskmanager.numberOfTaskSlots: 4

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      tail -f /dev/null
      " 

  postgres:
    image: ghusta/postgres-world-db:2.10
    ports:
      - "5432:5432"

# Without a network explicitly defined, you hit this Hive/Thrift error
# java.net.URISyntaxException Illegal character in hostname
# https://github.com/TrivadisPF/platys-modern-data-platform/issues/231
networks:
  default:
     name: zaphod
