---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heimdall-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: heimdall-role
rules:
  - apiGroups:
      - ""
      - flink.apache.org
    resources:
      - flinkdeployments
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heimdall-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: heimdall-role
subjects:
  - kind: ServiceAccount
    name: heimdall-service-account
---
apiVersion: v1
kind: Pod
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  serviceAccountName: "heimdall-service-account"
  containers:
  - name: heimdall
    image: ghcr.io/sap1ens/heimdall:0.7.0
    ports:
    - containerPort: 8080
    env:
    - name: HEIMDALL_ENDPOINT_PATH_PATTERNS_FLINK_UI
      value: "http://localhost/$jobName/"
---
kind: Service
apiVersion: v1
metadata:
  name: heimdall
spec:
  selector:
    app: heimdall
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdall
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /heimdall(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: heimdall-service
                port:
                  number: 8080
---
