name: flink-tx-cdc-aggregation
services:

  mysql:
    hostname: mysql
    image: quay.io/debezium/example-mysql:3.0.1.Final
    ports:
      - 3306:3306
    command: ["--default-authentication-plugin=caching_sha2_password","--log-bin=binlog","--server-id=12345"]
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - TZ=UTC
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s
    networks:
      - my-network

  kafka:
    hostname: kafka
    image: quay.io/strimzi/kafka:0.43.0-kafka-3.8.0
    command: [
      "sh", "-c",
      "./bin/kafka-storage.sh format -t $${RANDOM_STORAGE_UUID} -c ./config/kraft/server.properties && bin/kafka-server-start.sh ./config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override num.partitions=$${KAFKA_NUM_PARTITIONS} --override group.min.session.timeout.ms=$${KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS}"
    ]
    ports:
      - 9092:9092
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: 100
      RANDOM_STORAGE_UUID: X6GgnrKiQJmebuL2rWU9dw
    networks:
      - my-network

  connect:
    hostname: connect
    image: quay.io/debezium/connect:3.0.1.Final
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - ENABLE_DEBEZIUM_KC_REST_EXTENSION=true
      - ENABLE_DEBEZIUM_SCRIPTING=true
    networks:
      - my-network

networks:
  my-network:
    name: flink-tx-cdc-aggregation
