services:
  jobmanager:
    build: ./flink
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager
      rest.flamegraph.enabled: true
  taskmanager:
    build: ./flink
    hostname: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4

  mysql:
    image: quay.io/debezium/example-mysql:3.0.4.Final
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=hunter2
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw

#  postgres:
#    image: quay.io/debezium/example-postgres:3.0.4.Final
#    ports:
#     - 5432:5432
#    environment:
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=hunter2

  elasticsearch:
    image: elastic/elasticsearch:7.17.25
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

networks:
  default:
     name: zaphod
