FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

RUN apt-get update && apt-get install -y curl zip unzip && rm -rf /var/lib/apt/lists/*

USER 1000:1000
WORKDIR /home/vscode

RUN curl -s "https://get.sdkman.io" | bash
SHELL ["/bin/bash", "-c"]
RUN source "/home/vscode/.sdkman/bin/sdkman-init.sh" \
        && sdk install java 17.0.14-tem \
        && sdk flush

RUN export JAVA_HOME=/home/vscode/.sdkman/candidates/java/current \
        && pip install apache-flink==1.20.0

RUN pip install sentence-transformers==3.4.0 langchain-community==0.3.16 langchain-huggingface==0.1.2 langchain-text-splitters==0.3.5
